config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get "users/show" => "users#show"
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'top#index'
  resources :foods do
    collection do
      get 'search'
    end
    resources :comments, only:[:create, :destroy]
  end
  post '/foods/:id/done' => 'foods#done',   as: 'done'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :food
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy
  mount_uploader :food_image, FoodUploader

  validates :title, length: { in: 1..255 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :foods, dependent: :destroy
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 20 }
  validates :profile, length: { maximum: 200 }
  mount_uploader :profile_image, ImageUploader

  def self.guest
    find_or_create_by!(email: 'aaa@aaa.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.password_confirmation = user.password
      user.name = 'ゲスト'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile_image])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :profile_image])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    food = Food.find(params[:food_id])
    comment = current_user.comments.new(comment_params)
    comment.food_id = food.id
    comment.save
    redirect_to food_path(food)
  end

  def destroy
    Comment.find_by(id: params[:id], food_id: params[:food_id]).destroy
    redirect_to food_path(params[:food_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_q, only: [:index, :search]
  before_action :ensure_user, only: [:edit, :update, :destroy]
  def index
    @today = Date.today
    @foods_done = Food.includes(:user).where.not(done_at:nil).page(params[:page]).per(9)
    @foods = Food.includes(:user).where(done_at:nil).order(:time).page(params[:page]).per(9)
    @foods_done_total = Food.includes(:user).where.not(done_at:nil)
    @foods_total = Food.includes(:user).where(done_at:nil).order(:time)
  end

  def new
    @food = Food.new
  end

  def show
    @today = Date.today
    @food = Food.find(params[:id])
    @comment = Comment.new
    @comments = @food.comments.page(params[:page]).per(6).reverse_order
    @comments_total = @food.comments
  end

  def create
    @food = current_user.foods.build(food_params)
    if @food.save
      redirect_to foods_path
    else
      render 'new'
    end
  end

  def edit
    @food = Food.find(params[:id])
  end

  def update
    @food = Food.find(params[:id])
    if @food.update(food_params)
      redirect_to foods_path#updateできたらindexページに行く
    else
      render 'edit'#できなかったらeditページのまま
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_path
  end

  def done
    @today = Date.today #今日の日付
    food = Food.find(params[:id])
    food.update(done_at: @today )#完了ボタンを押すとdone_atカラムに完了した日時を追加
    redirect_to :action => "index"
  end

  def search
    @today = Date.today
    @results_done = @q.result.includes(:user).where.not(done_at:nil).page(params[:page]).per(9)
    @results = @q.result.includes(:user).where(done_at:nil).order(:time).page(params[:page]).per(9)
    @results_done_total = @q.result.includes(:user).where.not(done_at:nil)
    @results_total = @q.result.includes(:user).where(done_at:nil).order(:time)
  end

  private
  def food_params
    params.require(:food).permit(:title, :content, :time, :done_at, :user_id, :food_image)
  end

  def set_q
    @q = Food.ransack(params[:q])
  end

  def ensure_user
    @foods = current_user.foods
    @food = @foods.find_by(id: params[:id])
    redirect_to foods_path unless @food
  end


end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: %i[update]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end
  def ensure_normal_user
    if resource.email == 'aaa@aaa.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新はできません。'
    end
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  protected
  
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user   # ユーザーをログインさせる
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<% breadcrumb :food_index %>
<div class="row">
  <div class="row-search">
    <div class="search_form">
      <%= render 'partial/search_form' %>
    </div>
  </div>
</div>
<div class="food-containers">
  <div class="food-container">
    <div class="food-container-head">
      <h1><i class="fas fa-list"></i> 食品一覧:<%= @foods_total.length %>件</h1>
        <div class="actions">
          <%= link_to new_food_path,class: "btn btn-primary btn-lg border border-white",style: "background-color: #cd853f;" do %>
            </span><i class="fas fa-pen"></i>
          <% end %>
        </div>
    </div>
    <% if @foods.length != 0 %>
      <div class="card-deck">
        <% @foods.each do |food| %>
          <% if (food.time - @today).to_i > -1 %>
            <div class="food col-md-4">
              <div class="card h-100">
                <div class="card-img-top">
                  <%= link_to food_path(food) do %>
                    <% if food.food_image? %>
                      <%= image_tag food.food_image.url %>
                    <% else %>
                      <%= image_tag("default.png") %>
                    <% end %>
                  <% end %>
                </div>
                <div class="card-body">
                  <div class="card-title">
                    <h5><%= food.title %></h5>
                  </div>
                </div>
                <ul class="list-group list-group-flush">
                  <li class="list-group-item">期限切れまで:<%= (food.time - @today).to_i %>日</li>
                </ul>
                <div class="card-body">
                  <div class="card-body-btn">
                  <% if food.user == current_user %>
                    <%= link_to food_path(food),class: "btn btn-warning",style: "color:white;, background-color: #FF8C00;" do %>
                      <span class="description_top">詳細</span><i class="fas fa-info"></i>
                    <% end %>
                    <%= link_to done_path(food.id), method: :post,class: "btn btn-success" do %>
                      <span class="description_top">消費</span><i class="fas fa-tasks"></i>
                    <% end %>
                    <%= link_to edit_food_path(food),class: "btn btn-info" do %>
                      <span class="description_top">編集</span><i class="fas fa-edit"></i>
                    <% end %>
                    <%= link_to food, method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-danger" do %>
                      <span class="description_top">削除</span><i class="fas fa-trash-alt"></i>
                    <% end %>
                  <% else %>
                    <%= link_to food_path(food),class: "btn btn-warning",style: "color:white;, background-color: #FF8C00;" do %>
                      <span class="description_top">詳細</span><i class="fas fa-info"></i>
                    <% end %>
                  <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% else %>
            <div class="food col-md-4">
              <div class="card h-100">
                <div class="card-img-top">
                  <%= link_to food_path(food) do %>
                    <% if food.food_image? %>
                      <%= image_tag food.food_image.url %>
                    <% else %>
                      <%= image_tag("default.png") %>
                    <% end %>
                  <% end %>
                </div>
                <div class="card-body">
                  <div class="card-title">
                    <h5><span class="badge badge-pill badge-danger"><i class="fas fa-exclamation"></i></span><%= food.title %></h5>
                  </div>
                </div>
                <ul class="list-group list-group-flush">
                  <li class="list-group-item">現在<%= (food.time - @today).to_i * -1 %>日、賞味期限切れです。</li>
                </ul>
                <div class="card-body">
                  <div class="card-body-btn">
                    <% if food.user == current_user %>
                    <%= link_to food_path(food),class: "btn btn-warning",style: "color:white;, background-color: #FF8C00;" do %>
                      <span class="description_top">詳細</span><i class="fas fa-info"></i>
                    <% end %>
                    <%= link_to done_path(food.id), method: :post,class: "btn btn-success" do %>
                      <span class="description_top">消費</span><i class="fas fa-tasks"></i>
                    <% end %>
                    <%= link_to edit_food_path(food),class: "btn btn-info" do %>
                      <span class="description_top">編集</span><i class="fas fa-edit"></i>
                    <% end %>
                    <%= link_to food, method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-danger" do %>
                      <span class="description_top">削除</span><i class="fas fa-trash-alt"></i>
                    <% end %>
                  <% else %>
                    <%= link_to food_path(food),class: "btn btn-warning",style: "color:white;, background-color: #FF8C00;" do %>
                      <span class="description_top">詳細</span><i class="fas fa-info"></i>
                    <% end %>
                  <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <% else %>
        <h3>このページに食品はありません</h3>
      <% end %> 
    </div>
    <div class="food-container">
      <h1><i class="fas fa-tasks"></i> 消費した食品:<%= @foods_done_total.length %>件</h1>
      <% if @foods_done.length != 0 %>
      <div class="card-deck">
      <% @foods_done.each do |food| %>
        <div class="food col-md-4">
          <div class="card h-100">
            <div class="card-img-top">
              <%= link_to food_path(food) do %>
                <% if food.food_image? %>
                  <%= image_tag food.food_image.url %>
                <% else %>
                  <%= image_tag("default.png") %>
                <% end %>
              <% end %>
            </div>
            <div class="card-body">
              <div class="card-title">
                <h5><%= food.title %></h5>
              </div>
            </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">消費日:<%= food.done_at.strftime('%Y-%m-%d') %></li>
              </ul>
            <div class="card-body">
              <div class="card-body-btn">
              <% if food.user == current_user %>
                <%= link_to food_path(food),class: "btn btn-warning",style: "color:white;, background-color: #FF8C00;" do %>
                  <span class="description_top">詳細</span><i class="fas fa-info"></i>
                <% end %>
                <%= link_to food, method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-danger" do %>
                  <span class="description_top">削除</span><i class="fas fa-trash-alt"></i>
                <% end %>
              <% else %>
                <%= link_to food_path(food),class: "btn btn-warning",style: "color:white;, background-color: #FF8C00;" do %>
                  <span class="description_top">詳細</span><i class="fas fa-info"></i>
                <% end %>
              <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <% else %>
      <h3>このページに消費した食品はありません</h3>
    <% end %>
  </div>
</div>
<div id="page_top"><a href="#"><%= image_pack_tag 'up.png' %></a></div>
<%= paginate @foods %>

app/views/foods/index.html_sub.erb
<% breadcrumb :food_show %>
<div class="row">
  <div class="row-search">
    <div class="search_form">
      <%= render 'partial/search_form' %>
    </div>
  </div>
</div>
<div class="food-containers">
  <div class="food-container">
    <div class="food-container-head">
      <h1>食品一覧:<%= @foods_total.length %>件</h1>
        <div class="actions">
          <%= link_to '食品追加', new_food_path,class: "btn btn-primary border border-white",style: "background-color: #cd853f;" %>
        </div>
    </div>
    <% if @foods.length != 0 %>
      <div class="card-deck">
      <% @foods.each do |food| %>
        <% if (food.time - @today).to_i > -1 %>
          <div class="food col-sm-4">
            <div class="card h-100">
              <div class="card-img-top">
                <% if food.food_image? %>
                  <%= image_tag food.food_image.url %>
                <% else %>
                  <%= image_tag("default.png") %>
                <% end %>
              </div>
              <div class="card-body">
                <div class="card-title">
                  <h5><%= food.title %></h5>
                </div>
                <div class="card-text">
                  <p><%= food.content %></p>
                </div>
              </div>
                <ul class="list-group list-group-flush">
                  <li class="list-group-item">賞味期限:<%= food.time %></li>
                  <li class="list-group-item">期限切れまで:<%= (food.time - @today).to_i %>日</li>
                </ul>
              <div class="card-body">
                <div class="card-body-btn">
                  <%= link_to '消費', done_path(food.id), method: :post,class: "btn btn-success" %>
                  <%= link_to '編集', edit_food_path(food),class: "btn btn-info" %>
                  <%= link_to '削除', food, method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-danger" %>
                </div>
              </div>
            </div>
          </div>
        <% else %>
          <div class="food col-sm-4">
            <div class="card h-100">
              <div class="card-img-top">
                <% if food.food_image? %>
                  <%= image_tag food.food_image.url %>
                <% else %>
                  <%= image_tag("default.png") %>
                <% end %>
              </div>
              <div class="card-body">
                <div class="card-title">
                  <h5><span class="badge badge-pill badge-warning">注意</span><%= food.title %></h5>
                </div>
                <div class="card-text">
                  <p><%= food.content %></p>
                </div>
              </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">賞味期限:<%= food.time %></li>
                <li class="list-group-item">現在<%= (food.time - @today).to_i * -1 %>日、賞味期限切れです。</li>
              </ul>
              <div class="card-body">
                <div class="card-body-btn">
                  <%= link_to '消費', done_path(food.id), method: :post,class: "btn btn-success" %>
                  <%= link_to '編集', edit_food_path(food),class: "btn btn-info" %>
                  <%= link_to '削除', food, method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-danger" %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <% else %>
      <h3>このページに食品はありません</h3>
    <% end %> 
  </div>
  <div class="food-container">
      <h1>消費した食品:<%= @foods_done_total.length %>件</h1>
    <% if @foods_done.length != 0 %>
      <div class="card-deck">
      <% @foods_done.each do |food| %>
        <div class="food col-sm-4">
          <div class="card h-100">
            <div class="card-img-top">
              <% if food.food_image? %>
                <%= image_tag food.food_image.url %>
              <% else %>
                <%= image_tag("default.png") %>
              <% end %>
            </div>
            <div class="card-body">
              <div class="card-title">
                <h5><%= food.title %></h5>
              </div>
              <div class="card-text">
                <p><%= food.content %></p>
              </div>
            </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">消費日:<%= food.done_at.strftime('%Y-%m-%d') %></li>
              </ul>
            <div class="card-body">
              <%= link_to '削除', food, method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-danger" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <% else %>
      <h3>このページに消費した食品はありません</h3>
    <% end %>
  </div>
</div>
<div id="page_top"><a href="#"><%= image_pack_tag 'up.png' %></a></div>
<%= paginate @foods %>

app/views/foods/index2.html.erb
<div class="row">
  <div class="search_form">
    <%= render 'partial/search_form' %>
  </div>
</div>
<div class="food-containers">
<div class="food-container">
<div class="food-container-head">
  <h1>食品一覧</h1>
  <div class="actions">
    <%= link_to '食品追加', new_food_path,class: "btn btn-primary border border-white",style: "background-color: #cd853f;" %>
  </div>
</div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>食品</th>
        <th>詳細</th>
        <th>賞味期限</th>
        <th>期限切れまで</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @foods.each do |food| %>
      <% if (food.time - @today).to_i > -1 %>
      <tr>
        <td><%= food.title %></td>
        <td><%= food.content %></td>
        <td><%= food.time %></td>
        <td><%= (food.time - @today).to_i %>日</td>
        <td><%= link_to '消費', done_path(food.id), method: :post,class: "btn btn-success" %></td>
        <td><%= link_to '編集', edit_food_path(food),class: "btn btn-info" %></td>
        <td><%= link_to '削除', food, method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-danger" %></td>
      </tr>
      <% else %>
      <tr>
        <td><%= food.title %></td>
        <td><%= food.content %></td>
        <td><%= food.time %></td>
        <td>現在<%= (food.time - @today).to_i * -1 %>日、賞味期限切れです。</td>
        <td><%= link_to '消費', done_path(food.id), method: :post,class: "btn btn-success" %></td>
        <td><%= link_to '編集', edit_food_path(food),class: "btn btn-info" %></td>
        <td><%= link_to '削除', food, method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-danger" %></td>
      </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<div class="food-container">
<h1>消費した食品</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>食品</th>
      <th>詳細</th>
      <th>消費日</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @foods_done.each do |food| %>
    <tr>
      <td><%= food.title %></td>
      <td><%= food.content %></td>
      <td><%= food.done_at.strftime('%Y-%m-%d') %></td>
      <td></td>
      <td></td>
      <td></td>
      <td><%= link_to '削除', food, method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-danger" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<%= paginate @foods %>

app/views/foods/index_first.html.erb
<div class="row">
  <div class="search_form">
    <%= render 'partial/search_form' %>
  </div>
</div>
<div class="food-containers">
<div class="food-container">
<div class="food-container-head">
  <h1>食品一覧</h1>
  <div class="actions">
    <%= link_to '食品追加', new_food_path,class: "btn btn-primary border border-white",style: "background-color: #cd853f;" %>
  </div>
</div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>食品</th>
        <th>詳細</th>
        <th>賞味期限</th>
        <th>期限切れまで</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @foods.each do |food| %>
      <% if (food.time - @today).to_i > -1 %>
      <tr>
        <td><%= food.title %></td>
        <td><%= food.content %></td>
        <td><%= food.time %></td>
        <td><%= (food.time - @today).to_i %>日</td>
        <td><%= link_to '消費', done_path(food.id), method: :post,class: "btn btn-success" %></td>
        <td><%= link_to '編集', edit_food_path(food),class: "btn btn-info" %></td>
        <td><%= link_to '削除', food, method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-danger" %></td>
      </tr>
      <% else %>
      <tr>
        <td><%= food.title %></td>
        <td><%= food.content %></td>
        <td><%= food.time %></td>
        <td>現在<%= (food.time - @today).to_i * -1 %>日、賞味期限切れです。</td>
        <td><%= link_to '消費', done_path(food.id), method: :post,class: "btn btn-success" %></td>
        <td><%= link_to '編集', edit_food_path(food),class: "btn btn-info" %></td>
        <td><%= link_to '削除', food, method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-danger" %></td>
      </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<div class="food-container">
<h1>消費した食品</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>食品</th>
      <th>詳細</th>
      <th>消費日</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @foods_done.each do |food| %>
    <tr>
      <td><%= food.title %></td>
      <td><%= food.content %></td>
      <td><%= food.done_at.strftime('%Y-%m-%d') %></td>
      <td></td>
      <td></td>
      <td></td>
      <td><%= link_to '削除', food, method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-danger" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
<%= paginate @foods %>

app/views/foods/search2.html.erb
<div class="food-containers">
<div class="food-container">
<div class="food-container-head-search">
  <h1>検索結果</h1>
  <h2>食品一覧</h2>
</div>
  <% if @results.length != 0 %>
    <table class="table table-striped">
    <thead>
      <tr>
        <th>食品</th>
        <th>詳細</th>
        <th>賞味期限</th>
        <th>期限切れまで</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @results.each do |food| %>
      <% if (food.time - @today).to_i > -1 %>
      <tr>
        <td><%= food.title %></td>
        <td><%= food.content %></td>
        <td><%= food.time %></td>
        <td><%= (food.time - @today).to_i %>日</td>
        <td><%= link_to '消費', done_path(food.id), method: :post,class: "btn btn-success" %></td>
        <td><%= link_to '編集', edit_food_path(food),class: "btn btn-info" %></td>
        <td><%= link_to '削除', food, method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-danger" %></td>
      </tr>
      <% else %>
      <tr>
        <td><%= food.title %></td>
        <td><%= food.content %></td>
        <td><%= food.time %></td>
        <td>現在<%= (food.time - @today).to_i * -1 %>日、賞味期限切れです。</td>
        <td><%= link_to '消費', done_path(food.id), method: :post,class: "btn btn-success" %></td>
        <td><%= link_to '編集', edit_food_path(food),class: "btn btn-info" %></td>
        <td><%= link_to '削除', food, method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-danger" %></td>
      </tr>
      <% end %>
      <% end %>
    <% else %>
      <h3>検索結果はありません</h3>
    <% end %>
    </tbody>
  </table>
</div>

<div class="food-container">
<h2>消費した食品</h2>

  <% if @results_done.length != 0 %>
    <table class="table table-striped">
  <thead>
    <tr>
      <th>食品</th>
      <th>詳細</th>
      <th>消費日</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @results_done.each do |food| %>
    <tr>
      <td><%= food.title %></td>
      <td><%= food.content %></td>
      <td><%= food.done_at.strftime('%Y-%m-%d') %></td>
      <td></td>
      <td></td>
      <td></td>
      <td><%= link_to '削除', food, method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-danger" %></td>
    </tr>
    <% end %>
  <% else %>
    <h3>検索結果はありません</h3>
  <% end %>
  </tbody>
</table>
  
<div class="actions">
  <%= link_to '戻る', foods_path, class: "btn btn-outline-secondary btn-sm" %>
</div>
</div>
</div>
<%= paginate @results %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class = "error">
     <ul>
        <% model.errors.full_messages.each do |message| %>
           <li><%= message %></li>
	    <% end %>
     </ul>
  </div>
<% end %>

app/views/partial/_comment.html.erb
<h1>コメント：<%= @comments_total.count %>件</h1>
<div class="card-deck">
  <% @comments.each do |comment| %>
    <div class="food col-md-4">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title"><%= comment.user.name %></h5>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><%= comment.comment %></li>
          <li class="list-group-item">コメント日時:<%= comment.created_at.strftime('%Y-%m-%d') %></li>
        </ul>
        <% if comment.user == current_user %>
          <div class="card-body">
            <div class="card-body-btn">
              <%= link_to food_comment_path(comment.food, comment), method: :delete, data: { confirm: '本当に削除しますか?' },class: "btn btn-danger" do %>
                <span class="description_comment">削除</span><i class="fas fa-trash-alt"></i>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<%= paginate @comments %>